# Generated by Django 5.0 on 2024-04-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_borrower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrower',
        ),
    ]
